lib/jf_web/router.ex
defmodule JfWeb.Router do
  use JfWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug JfWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  defimpl Phoenix.HTML.Safe, for: Map do
    def to_iodata(data), do: data |> Poison.encode! |> Plug.HTML.html_escape
  end

  scope "/", JfWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/enderecos", EnderecoController
    resources "/produtos", ProdutoController
    resources "/cardapios", CardapioController
    resources "/restaurantes", RestauranteController
    resources "/pedidos", PedidoController
    resources "/cart", CartController
    resources "/messages", MessageController
    resources "/admins", AdminController


  end

  scope "/auth", JfWeb do
    pipe_through :browser

    get "/signout", UserController, :signout
    get "/:provider", UserController, :request
    get "/:provider/callback", UserController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", JfWeb do
  #   pipe_through :api
  # end
end

lib/jf_web/views/layout_view.ex
defmodule JfWeb.LayoutView do
  use JfWeb, :view
end

lib/jf_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jf!</title>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="light-blue" role="navigation">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">Jaguaribe Food</a>
        <%= if @conn.assigns[:user] do %>
          <ul id="dropdown1" class="dropdown-content">
            <!--<li class="divider"></li>-->
            <li> <%= link "Sair", to: user_path(@conn, :signout) %></li>
          </ul>
          <div class="nav-wrapper">
            <ul class="right hide-on-med-and-down">
              <li><%= link "Meus pedidos", to: pedido_path(@conn, :index) %></li>
              <li><%= link "Carrinho", to: cart_path(@conn, :index) %></li>
              <li><%= link "Endereços", to: endereco_path(@conn, :index) %></li>
              <li><a class="dropdown-trigger" href="/" data-target="dropdown1"><%= @conn.assigns.user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
          </div>
        <% else %>
          <%= if signed_in?(@conn) do %>
              <ul id="dropdown1" class="dropdown-content">
              <!--<li class="divider"></li>-->
              <li> <%= link "Sair", to: user_path(@conn, :signout) %></li>
              </ul>
            <div class="nav-wrapper">
              <ul class="right hide-on-med-and-down">
                <li><%= link "Meus produtos", to: produto_path(@conn, :index) %></li>
                <li><%= link "Pedidos", to: pedido_path(@conn, :index) %></li>
                <li><%= link "Mensagens", to: message_path(@conn, :index) %></li>
                <li><a class="dropdown-trigger" href="/" data-target="dropdown1">Bugger<i class="material-icons right">arrow_drop_down</i></a></li>
              </ul>
            </div>
          <% else %>
            <div class="nav-wrapper">
              <ul class="right hide-on-med-and-down">
                <li><%= link "Carrinho", to: cart_path(@conn, :index) %></li>
                <li><%= link "Entrar com Facebook", to: user_path(@conn, :request, "facebook") %></li>
                <li><%= link "Entrar Restaurante", to: admin_path(@conn, :new) %></li>
              </ul>
            </div>
          <% end %>
        <% end %>

    </nav>

    <div class="container">
      <header class="header">

      </header>

     
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>